# Generated by Django 6.0.4 on 2026-06-19 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_device_streaming_standby_count'),
        ('tenants', '0003_tenant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterMetricSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('node_role', models.CharField(blank=True, max_length=10)),
                ('streaming_standby_count', models.IntegerField(default=0)),
                ('failover_count', models.IntegerField(default=0)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='metric_samples', to='devices.device')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_samples', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['tenant', '-captured_at'], name='devices_clu_tenant__d2c715_idx')],
            },
        ),
    ]
