# Generated by Django 6.0.6 on 2026-06-19 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_clustermetricsample'),
        ('tenants', '0003_tenant_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentVerdict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('health', models.CharField(blank=True, max_length=20)),
                ('risk_level', models.CharField(choices=[('sain', 'Sain'), ('surveiller', 'À surveiller'), ('critique', 'Critique')], default='surveiller', max_length=12)),
                ('anomaly_score', models.IntegerField(default=0)),
                ('summary', models.TextField(blank=True)),
                ('recommendation', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('mistral', 'Mistral AI'), ('local', 'Analyse locale (repli)')], default='local', max_length=12)),
                ('features', models.JSONField(blank=True, default=dict)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_verdicts', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', '-created_at'], name='devices_age_tenant__99a34c_idx')],
            },
        ),
    ]
