# Generated by Django 6.0.6 on 2026-06-19 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_agentverdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentverdict',
            name='details',
            field=models.TextField(blank=True),
        ),
    ]
