# Generated by Django 6.0.6 on 2026-06-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_agentverdict_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='epoch',
            field=models.IntegerField(default=0, help_text='Époque du nœud = timeline PostgreSQL (incrémenté à chaque promotion). Sert au fencing : un primaire avec une époque périmée est clôturé.'),
        ),
    ]
